# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dash < Formula
  desc "Project dev process dashboard TUI"
  homepage "https://github.com/davydeh/dash"
  version "0.3.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/davydeh/dash/releases/download/v0.3.0/dash_0.3.0_darwin_amd64.tar.gz"
    sha256 "248ca18e320c8feeadcd1c96c28f8f9700ea7e32e8bd4ba1ae741c9a1f2191ad"

    define_method(:install) do
      bin.install "dash"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/davydeh/dash/releases/download/v0.3.0/dash_0.3.0_darwin_arm64.tar.gz"
    sha256 "7430169907a95bef2c26c120a3ca40c9fa8bd5947e5c563684e34f45f31dab8c"

    define_method(:install) do
      bin.install "dash"
    end
  end
end
