# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dash < Formula
  desc "Project dev process dashboard TUI"
  homepage "https://github.com/davydeh/dash"
  version "0.1.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/davydeh/dash/releases/download/v0.1.1/dash_0.1.1_darwin_amd64.tar.gz"
    sha256 "518d2f91063a98815346c976fa89a9f624c29c23fb28419d3374880526d57e2d"

    define_method(:install) do
      bin.install "dash"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/davydeh/dash/releases/download/v0.1.1/dash_0.1.1_darwin_arm64.tar.gz"
    sha256 "45d186c850e6c29ff32287a1a307829567dde1fcf8ed5b032e9967e5ab8857d2"

    define_method(:install) do
      bin.install "dash"
    end
  end
end
