# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DashDev < Formula
  desc "Project dev process dashboard TUI"
  homepage "https://github.com/davydeh/dash"
  version "0.3.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/davydeh/dash/releases/download/v0.3.1/dash_0.3.1_darwin_amd64.tar.gz"
    sha256 "54a54b09d555372282bd8c34010b68071df3dfcca7e931e64b78ab5bc949e8f4"

    define_method(:install) do
      bin.install "dash"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/davydeh/dash/releases/download/v0.3.1/dash_0.3.1_darwin_arm64.tar.gz"
    sha256 "cc9dbb5345e7fd2ba751db502bbe27ca772e55741d0d81b607270e8cda9ab900"

    define_method(:install) do
      bin.install "dash"
    end
  end
end
